name: flutter_application_mimascota_plus
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.2
  provider: ^6.1.5
  uuid: ^4.5.1
  flutter_lints: ^6.0.0
  google_fonts: ^6.3.2
  image_picker: ^1.2.0
  firebase_storage: ^12.4.10
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # ðŸ‘‡ Agrega tus recursos aquÃ­
  assets:
    - assets/icons/